"""Add is_verified column to users and remove verified_at

Revision ID: d91ff992a079
Revises: 6bd5cfe9e57a
Create Date: 2025-05-20 06:34:15.248505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd91ff992a079'
down_revision: Union[str, None] = '6bd5cfe9e57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
