"""upgraded education and experience table

Revision ID: ea3e63594d15
Revises: 97e4d50bcc7e
Create Date: 2025-06-26 05:12:05.107425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea3e63594d15'
down_revision: Union[str, None] = '97e4d50bcc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define enum type
learning_mode_enum = sa.Enum('remote', 'in_person', 'hybrid', name='learningmodeenum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Education', sa.Column('course', sa.String(length=150), nullable=True))
    op.add_column('Education', sa.Column(
        'learning_mode',
        sa.Enum('remote', 'in_person', 'hybrid', name='learningmodeenum'),
        nullable=True
    ))

    # Add new columns to existing Experience table
    op.add_column('Experience', sa.Column(
        'job_mode',
        sa.Enum('remote', 'in_person', 'hybrid', name='learningmodeenum'),
        nullable=True
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Education', 'course')
    op.drop_column('Education', 'learning_mode')
    op.drop_column('Experience', 'job_mode')

    learning_mode_enum.drop(op.get_bind())
    # ### end Alembic commands ###
